import StaticPageLayout from "@/components/StaticPageLayout";

export default function TermsPage() {
  return (
    <StaticPageLayout title="Terms of Use">
      <div className="text-center mb-12">
        <span className="inline-block px-3 py-1 rounded-full bg-teal-50 text-teal-700 text-sm font-medium mb-4">Legal</span>
        <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-2">Terms of Use</h1>
        <p className="text-sm text-gray-500">Effective Date: 09-30-2025</p>
      </div>

      <div className="space-y-8 text-gray-700 leading-relaxed">
        <p>
          By using Requisor AI, you agree to these terms.
        </p>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">1. Service</h2>
          <p>
            Requisor provides AI-generated product insights, plans, and execution outputs.
            Our platform helps teams transform conversations, feedback, and usage data into
            structured product decisions and actionable plans.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">2. User Responsibilities</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>Provide accurate data when using the platform</li>
            <li>Use the platform lawfully and in accordance with these terms</li>
            <li>Maintain the security of your account credentials</li>
            <li>Not attempt to access other users' data or accounts</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">3. AI Disclaimer</h2>
          <p>
            Outputs generated by Requisor AI are AI-generated suggestions and should be reviewed
            by qualified individuals before use. We do not guarantee the accuracy, completeness,
            or suitability of AI-generated content for any specific purpose.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">4. Data Ownership</h2>
          <p>
            Users retain full ownership of their data. You grant Requisor a limited license to
            process your data solely to provide the service. We do not claim ownership of any
            content you upload or create through the platform.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">5. Account Termination</h2>
          <p>
            We may suspend or terminate accounts that violate these terms or engage in misuse
            of the platform. You may close your account at any time, and your data will be
            deleted in accordance with our Privacy Policy.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">6. Limitation of Liability</h2>
          <p>
            The service is provided "as is" without warranties of any kind, express or implied.
            Requisor shall not be liable for any indirect, incidental, special, or consequential
            damages arising from use of the platform.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">7. Changes to Terms</h2>
          <p>
            We may update these terms from time to time. Continued use of the service after
            changes constitutes acceptance of the updated terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">8. Contact</h2>
          <p>
            For questions about these terms, contact us at{" "}
            <a href="mailto:support@requisor.io" className="text-teal-600 hover:text-teal-700 font-medium">
              support@requisor.io
            </a>
          </p>
        </section>
      </div>
    </StaticPageLayout>
  );
}
